### ISSUE TITLE
enhanced-personal-folders no longer working with PowerShell 7

### ISSUE THREAD

**Issue by mynameisalbertb** [thycotic-ps/secretserver#14]
I'm testing out enhanced folders for a client in a skytap lab and have run into an error of: 

"Script Error: The term 'New-TssSession' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again"

This is an on premise install in skytap, utilizing a domain service account along with the domain scripting arguments.  

I was told that the recent move to v7 for platform purposes has broken Secret Server as it still only supports V5 of PowerShell.

**Comment by jagger** [comment]
Update #17 moved process to bare API calls please verify
