### ISSUE TITLE
Thycotic PowerShell module

### ISSUE THREAD

**Issue by Jamlmalik12** [thycotic-ps/secretserver#28]
Hii Everyone!

I'm trying to create a Sync Secret pipeline.
I have already installed the Thycotic Module by powershell 7.
I can see the list of installed modules. However, when I test the script, I receive an error message saying that it was not possible to install the Thycotic.SecretServer module, which I already have installed on my Distributed Engine.
After installing the module, do I need any further configuration?
Here's the script I'm using
![Captura de tela 2024-04-03 163755](https://github.com/thycotic-ps/secretserver/assets/145500072/f63f992f-0f56-461f-8227-3568868fda33)

secretserver/event-pipelines/sync-secrets
/sync-secrets-v2.ps1

**Comment by jagger** [comment]
Secret Server internally uses Windows Powershell (V5) and not PowerShell Core (V6+) so you cannot use the thycotic.secretserver module for scripts launched from within Secret Server, it is for connections initiated fully outside of the product

**Comment by Jamlmalik12** [comment]
Right, if you can help me,
What do I need to do to run this sync secret pipeline?
In my SaaS enviroment with distributed Engine
