### ISSUE TITLE
Bad URLs in Linked Secret Dependency Changer read.me

### ISSUE THREAD

**Issue by MillanAireson** [thycotic-ps/secretserver#35]
Reference to how to configure WINRM should be:

https://docs.delinea.com/online-help/secret-server/api-scripting/scripting/powershell-scripts/powershell-winrm/configuring-winrm-powershell/index.htm?Highlight=configuring%20winrm

**Comment by jagger** [comment]
Can you provide a link to the document(s) with bad URLs?

**Comment by MillanAireson** [comment]
https://github.com/thycotic-ps/secretserver/tree/main/dependency-changers/secretserver-linked-secrets#readme

**Comment by jagger** [comment]
Closed by #36 

Thank you :+1:
